# Generated by Django 5.0.6 on 2026-09-27 10:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20)),
                ('name_label', models.CharField(blank=True, default='', max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('CLEANING', 'Cleaning / Sanitizing')], default='AVAILABLE', max_length=20)),
                ('qr_version', models.PositiveIntegerField(default=1, help_text='Incrementing revokes all previously printed QR codes.')),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=100.0)),
                ('height', models.FloatField(default=100.0)),
                ('rotation', models.FloatField(default=0.0)),
                ('shape', models.CharField(choices=[('RECTANGLE', 'Rectangle'), ('ROUND', 'Round'), ('SQUARE', 'Square')], default='RECTANGLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.section')),
            ],
            options={
                'db_table': 'tables_table',
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Dining'), ('CLOSED', 'Closed & Paid')], default='ACTIVE', max_length=20)),
                ('guest_session_version', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tables.table')),
            ],
            options={
                'db_table': 'tables_tablesession',
            },
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['restaurant', 'status'], name='tables_tabl_restaur_715b06_idx'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('restaurant', 'table_number'), name='unique_table_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='tablesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('table',), name='unique_active_session_per_table'),
        ),
    ]
