# Generated by Django 5.0.6 on 2026-09-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('CALL_WAITER', 'Call Waiter'), ('WATER', 'Bring Water'), ('EXTRA_PLATE', 'Extra Plates / Cutlery'), ('BILL', 'Request Bill'), ('OTHER', 'Other Request')], default='CALL_WAITER', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to='tables.tablesession')),
            ],
            options={
                'db_table': 'operations_customerrequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
