# Generated by Django 5.0.6 on 2026-09-27 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(default='WAITER', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (08:00 - 16:00)'), ('EVENING', 'Evening (16:00 - 24:00)'), ('NIGHT', 'Night (24:00 - 08:00)'), ('FULL_DAY', 'Full Day')], default='MORNING', max_length=30)),
                ('is_present', models.BooleanField(default=True)),
                ('pin_code', models.CharField(blank=True, default='1234', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='restaurants.restaurant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_member',
            },
        ),
    ]
