# Generated by Django 5.0.6 on 2026-09-27 10:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine-In'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery')], default='DINE_IN', max_length=20)),
                ('source', models.CharField(choices=[('CUSTOMER_QR', 'Customer Table QR'), ('WAITER', 'Waiter Tablet'), ('POS', 'POS Cashier'), ('ADMIN', 'Admin')], default='CUSTOMER_QR', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed & Sent to Kitchen'), ('COMPLETED', 'Fully Completed & Served'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant')),
                ('table_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tables.tablesession')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField(default=1, help_text='Designates specific seat/guest for accurate Split Bills')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8)),
                ('unit_price_at_order', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('course', models.CharField(choices=[('COURSE_1', 'Course 1 (Starters & Beverages)'), ('COURSE_2', 'Course 2 (Main Course)'), ('COURSE_3', 'Course 3 (Desserts & After)')], default='COURSE_2', max_length=20)),
                ('kitchen_status', models.CharField(choices=[('NEW', 'New Ticket'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'In Preparation'), ('READY', 'Ready for Pickup'), ('SERVED', 'Served to Table'), ('VOIDED', 'Voided')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'orders_orderitem',
            },
        ),
        migrations.CreateModel(
            name='OrderItemConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=3, max_digits=12)),
                ('base_unit', models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('LITER', 'Liter'), ('ML', 'Milliliter'), ('PIECE', 'Piece / Unit')], max_length=20)),
                ('recipe_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.inventoryitem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='orders.orderitem')),
            ],
            options={
                'db_table': 'orders_orderitemconsumption',
            },
        ),
        migrations.CreateModel(
            name='OrderItemSplitShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_shares', to='orders.orderitem')),
            ],
            options={
                'db_table': 'orders_orderitemsplitshare',
            },
        ),
    ]
