# Generated by Django 5.0.6 on 2026-09-27 10:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_service_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open & Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Fully Paid & Cleared'), ('VOIDED', 'Voided')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='restaurants.restaurant')),
                ('table_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='tables.tablesession')),
            ],
            options={
                'db_table': 'finance_bill',
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_cashsession',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'POS Card Terminal'), ('OTHER', 'Other / QR Wallet')], default='CASH', max_length=20)),
                ('payer_type', models.CharField(choices=[('FULL_TABLE', 'Full Bill Payment'), ('SEAT', 'Individual Seat / Guest Share'), ('CUSTOM', 'Custom Amount Split')], default='FULL_TABLE', max_length=20)),
                ('seat_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.bill')),
            ],
            options={
                'db_table': 'finance_payment',
            },
        ),
    ]
