# Generated by Django 5.0.6 on 2026-09-27 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(choices=[('POS', 'POS Terminal'), ('WAITER_TABLET', 'Waiter Tablet'), ('KITCHEN_DISPLAY', 'Kitchen Display'), ('CUSTOMER', 'Customer Terminal')], default='WAITER_TABLET', max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_ping', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'devices_device',
            },
        ),
    ]
