# Generated by Django 5.0.6 on 2026-09-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze Member'), ('SILVER', 'Silver VIP'), ('GOLD', 'Gold VIP'), ('PLATINUM', 'Platinum Elite')], default='BRONZE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='crm.customer')),
            ],
            options={
                'db_table': 'loyalty_account',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('EARN', 'Earned from Order'), ('REDEEM', 'Redeemed for Reward'), ('ADJUSTMENT', 'Manual Adjustment'), ('REVERSAL', 'Void Reversal')], max_length=20)),
                ('points_delta', models.IntegerField(help_text='Positive for earned, negative for spent')),
                ('points_balance_after', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='loyalty.loyaltyaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'db_table': 'loyalty_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
