# Generated by Django 5.0.6 on 2026-09-27 10:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'crm_customer',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveSmallIntegerField(help_text='1 to 5 stars')),
                ('food_rating', models.PositiveSmallIntegerField(default=5)),
                ('service_rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('table_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tables.tablesession')),
            ],
            options={
                'db_table': 'crm_feedback',
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('restaurant', 'phone'), name='unique_customer_phone_per_restaurant'),
        ),
    ]
