# Generated by Django 5.0.6 on 2026-09-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'reports_dailysnapshot',
                'unique_together': {('restaurant', 'report_date')},
            },
        ),
    ]
